# ======================
# ğŸ”– Informasi Dasar Situs
# ======================
title: "MyStyle"
description: "https://mystyle.my.id"
author: "Mystyle"
url: "https://mystyle.my.id"
baseurl: "" # kosongkan jika domain utama (bukan subfolder)
lang: "id"
theme_color: "#150033"
default_image: "/assets/css/thumb.png"

# ======================
# âš™ï¸ Konfigurasi Jekyll
# ======================
markdown: kramdown
timezone: "Asia/Jakarta"
permalink: /:title/ # gunakan nama file sebagai URL

# ======================
# ğŸ§© Plugin Bawaan GitHub Pages
# ======================
plugins:
  - jekyll-feed       # RSS feed otomatis
  - jekyll-seo-tag    # Meta tag otomatis (SEO)
  - jekyll-sitemap    # Sitemap.xml otomatis

# ======================
# ğŸ“¦ Pengaturan Default Front Matter
# ======================
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "none"
      author: "Mystyle"
      thumbnail: "/assets/css/thumb.png"
      description: "Postingan menarik dari MyStyle"
      tags: ["mystyle", "html", "css", "js"]

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Mystyle"
      thumbnail: "/assets/css/thumb.png"
      description: "Halaman MyStyle"
      tags: ["mystyle", "html", "css", "js"]

# ======================
# ğŸš« File/Foler yang Dikecualikan dari Build
# ======================
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - vendor/

# ======================
# ğŸ“‚ Folder Tambahan yang Disertakan
# ======================
include:
  - _pages
  - _posts

# ======================
# ğŸ”— Sosial Media (optional)
# ======================
social:
  instagram: "wildan.hidayat"
  tiktok: "wildanhidayat"
  github: "mystyl3"
